name-template: "$RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"
template: |
  Thank you for using the official [my-PV](https://www.my-pv.com/) Home Assistant integration.

  With Home Assistant 2026.10 the my-PV integration is part of Core and no custom integration is needed anymore to control the main features of your device.

  The custom integration still has some features that didn't make it in the Core release, but that will be resolved over time. We will keep the custom integration active for testing fixes and new functionality.

  We're looking forward to hear your experience with the new integration, please [create an issue](https://github.com/$OWNER/$REPOSITORY/issues) with your feedback and findings.

  The my-PV team

  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

categories:
  - title: "Breaking"
    label: "type: breaking"
  - title: "New"
    label: "type: feature"
  - title: "Bug Fixes"
    label: "type: bug"
  - title: "Maintenance"
    label: "type: maintenance"
  - title: "Documentation"
    label: "type: docs"
  - title: "Other changes"
  - title: "Dependency Updates"
    label: "type: dependencies"
    collapse-after: 5

version-resolver:
  major:
    labels:
      - "type: breaking"
  minor:
    labels:
      - "type: feature"
  patch:
    labels:
      - "type: bug"
      - "type: maintenance"
      - "type: docs"
      - "type: dependencies"
      - "type: security"

exclude-labels:
  - "skip-changelog"

exclude-contributors:
  - "dependabot"
  - "imgbot"
