name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  Thank you for using the official [my-PV](https://www.my-pv.com/) Home Assistant integration.
  
  We are working on bringing this integration into Home Assistant Core. Until that's done this custom integration contains all the functionality that will be in the Core integration.

  We're looking forward to hear your experience with the new integration.
  
  The my-PV team

  ## What’s Changed

  $CHANGES
  
  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

categories:
  - title: 'Breaking'
    label: 'type: breaking'
  - title: 'New'
    label: 'type: feature'
  - title: 'Bug Fixes'
    label: 'type: bug'
  - title: 'Maintenance'
    label: 'type: maintenance'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Other changes'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
    collapse-after: 5

version-resolver:
  major:
    labels:
      - 'type: breaking'
  minor:
    labels:
      - 'type: feature'
  patch:
    labels:
      - 'type: bug'
      - 'type: maintenance'
      - 'type: docs'
      - 'type: dependencies'
      - 'type: security'
  
exclude-labels:
  - 'skip-changelog'

exclude-contributors:
  - 'dependabot'
  - 'imgbot'
